"""`.env` utilities for :mod:`pypia_ctl`.

Purpose:
    Create or update `.env` with PIA_* keys used by
    :class:`~pypia_ctl.config.PiaSettings`. Never overwrites existing values.

Design:
    - Idempotent and conservative.
    - Pure local file I/O; no network or subprocess calls.

Attributes:
    DEFAULT_ENV_PATH (str): Default `.env` path (``.env``).

Functions:
    generate_env_text: Render default `.env` text from current settings/defaults.
    ensure_env_file: Create/append only missing keys to `.env` (non-destructive).

Examples:
    ::
        >>> from pypia_ctl.envtools import generate_env_text
        >>> isinstance(generate_env_text(), str)
        True
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .config import PiaSettings

DEFAULT_ENV_PATH: str = ".env"


@dataclass(slots=True, frozen=True)
class _EnvLine:
    """Minimal parsed representation of one `.env` line."""
    raw: str
    key: str | None = None
    value: str | None = None
    is_kv: bool = False
    is_comment: bool = False
    is_blank: bool = False


def _parse_env_lines(text: str) -> list[_EnvLine]:
    lines: list[_EnvLine] = []
    for raw in text.splitlines():
        s = raw.strip()
        if not s:
            lines.append(_EnvLine(raw=raw, is_blank=True))
            continue
        if s.startswith("#"):
            lines.append(_EnvLine(raw=raw, is_comment=True))
            continue
        if "=" in raw:
            key, val = raw.split("=", 1)
            lines.append(_EnvLine(raw=raw, key=key.strip(), value=val.strip(), is_kv=True))
        else:
            lines.append(_EnvLine(raw=raw))
    return lines


def _kv_map(lines: Iterable[_EnvLine]) -> dict[str, str]:
    out: dict[str, str] = {}
    for ln in lines:
        if ln.is_kv and ln.key is not None and ln.value is not None:
            out[ln.key] = ln.value
    return out


def _bool(v: bool) -> str:
    return "true" if v else "false"


def generate_env_text(*, settings: PiaSettings | None = None, with_comments: bool = True) -> str:
    """Generate default `.env` content from settings (non-secret placeholders).

    Args:
        settings: Optional settings object; defaults to ``PiaSettings()``.
        with_comments: Include explanatory comments.

    Returns:
        Rendered `.env` text safe to write as-is.

    Examples:
        ::
            >>> txt = generate_env_text()
            >>> "PIA_PROTOCOL" in txt
            True
    """
    s = settings or PiaSettings()
    pre = (
        "# .env generated by pypia_ctl\n"
        "# Re-run to append newly introduced keys. Existing keys are preserved.\n\n"
        if with_comments else ""
    )
    body = f"""# Core VPN
PIA_PROTOCOL={s.protocol}
PIA_DEFAULT_REGION={s.default_region}
PIA_PREFERRED_REGIONS={",".join(s.preferred_regions)}
PIA_RANDOMIZE_REGION={_bool(s.randomize_region)}

# Region filters
PIA_REGION_FILTERS__include_streaming={_bool(s.region_filters.include_streaming)}
PIA_REGION_FILTERS__include_countries={",".join(s.region_filters.include_countries)}
PIA_REGION_FILTERS__exclude_countries={",".join(s.region_filters.exclude_countries)}

# Proxy defaults for adapters (used by playwright/httpx/selenium helpers)
PIA_PROXY_KIND={s.proxy.kind}
PIA_PROXY_HOST={s.proxy.host or ""}
PIA_PROXY_PORT={(s.proxy.port or "")}
PIA_PROXY_USERNAME={s.proxy.username or ""}
PIA_PROXY_PASSWORD={s.proxy.password or ""}

# Optional plugins (comma-separated fully-qualified classes)
PIA_PLUGINS={",".join(s.plugins)}
"""
    return pre + body.rstrip() + "\n"


def ensure_env_file(path: str | Path = DEFAULT_ENV_PATH, *, settings: PiaSettings | None = None) -> Path:
    """Create or merge a `.env` file by appending missing PIA_* keys only.

    Args:
        path: Path to `.env`.
        settings: Optional settings object; defaults to ``PiaSettings()``.

    Returns:
        The path to the updated/created `.env`.

    Raises:
        OSError: If writing the file fails.

    Examples:
        ::
            >>> isinstance(".env", str)
            True
    """
    s = settings or PiaSettings()
    p = Path(path)

    desired_text = generate_env_text(settings=s, with_comments=True)
    desired_lines = _parse_env_lines(desired_text)
    desired = _kv_map(desired_lines)

    if not p.exists():
        p.write_text(desired_text, encoding="utf-8")
        return p

    existing_text = p.read_text(encoding="utf-8")
    existing_lines = _parse_env_lines(existing_text)
    existing = _kv_map(existing_lines)

    missing = {k: v for k, v in desired.items() if k not in existing}
    if not missing:
        return p

    append = "\n# Added by pypia_ctl\n" + "\n".join(f"{k}={v}" for k, v in missing.items()) + "\n"
    p.write_text(existing_text + append, encoding="utf-8")
    return p
