name: release
on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install PDM
        run: python -m pip install -U pip pdm

      - name: Install dependencies
        run: pdm install

      - name: Build artifacts
        run: pdm build

      - name: Twine check
        run: |
          python -m pip install -U twine
          twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install -U twine
          twine upload dist/*
